In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet('../data/nfl_data.parquet')
df.head()

,Week,Day,Date,Time,Winner/tie,H/A,Loser/tie,Pts Allowed Winner,Pts Allowed Loser,Yds Gained,TOs,Yds Allowed,Opp TOs,Tm Performance,Opp Performance,Spread,Spread Prcntl
0,1,Thu,2022-09-08,8:20PM,Buffalo Bills,@,Los Angeles Rams,31,10,413,4,243,3,0.524462,-0.890760,21,0.921037
1,1,Sun,2022-09-11,1:00PM,New Orleans Saints,@,Atlanta Falcons,27,26,385,1,416,2,0.025999,1.145263,1,0.134029
2,1,Sun,2022-09-11,1:00PM,Cleveland Browns,@,Carolina Panthers,26,24,355,0,261,1,-0.098617,0.890760,2,0.163157
3,1,Sun,2022-09-11,1:00PM,Chicago Bears,,San Francisco 49ers,19,10,204,1,331,2,-0.970927,-0.890760,9,0.460292
4,1,Sun,2022-09-11,1:00PM,Pittsburgh Steelers,@,Cincinnati Bengals,23,20,267,0,432,5,-0.472464,0.381754,3,0.196114

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 557 entries, 0 to 556
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Week                557 non-null    object
 1   Day                 557 non-null    object
 2   Date                557 non-null    object
 3   Time                557 non-null    object
 4   Winner/tie          557 non-null    object
 5   H/A                 557 non-null    object
 6   Loser/tie           557 non-null    object
 7   Pts Allowed Winner  557 non-null    object
 8   Pts Allowed Loser   557 non-null    object
 9   Yds Gained          557 non-null    object
 10  TOs                 557 non-null    object
 11  Yds Allowed         557 non-null    object
 12  Opp TOs             557 non-null    object
 13  Tm Performance      557 non-null    float64
 14  Opp Performance     557 non-null    float64
 15  Spread              557 non-null    int64
 16  Spread Prcntl       557 non-null    float64
dtypes: float64(3), int64(1), object(13)
memory usage: 74.1+ KB